### ISSUE TITLE
Work description issue

### ISSUE THREAD

**Issue by kumudbansal** [Newput-Time-tracker/Web-app#114]
Steps to reproduce:-

1. Enter work description where the number of character is greater than limit.
2. Click on save it shows 'Invalid Entry! Please make sure the correct format' error.
I think it should show either a proper error message or we should prevent the user to type if number of characters reached to  the limit.

**Comment by deeppatidar** [comment]
Created PR

**Comment by kumudbansal** [comment]
Verified changes. Thanks. Closing.
