### ISSUE TITLE
Verification Issue

### ISSUE THREAD

**Issue by kumudbansal** [Newput-Time-tracker/Web-app#119]
When i click on the verification it do not show the appropriate page. Please see attached screenshot.
![verify_account](https://cloud.githubusercontent.com/assets/15623790/10963962/098caf3a-83ca-11e5-839e-8e6de1d2e0e9.PNG)

**Comment by varshatyagi** [comment]
I have fixed this issue , please test it.

**Comment by kumudbansal** [comment]
Now it is showing another error message which says 'Email id or token is not correct'.

**Comment by kumudbansal** [comment]
Verified issue. Thanks. Closing.

**Comment by kumudbansal** [comment]
Please change error copy from  'Email id or token is not correct'  to ' Your Account is already verified.' if user try to re verify account.

**Comment by kumudbansal** [comment]
Thanks. Closing.
