### ISSUE TITLE
Wrong data in time sheet

### ISSUE THREAD

**Issue by kumudbansal** [Newput-Time-tracker/Web-app#135]
Export the timesheet and observe total hours, It is showing negative value and the total of working hours is wrong.

**Comment by kumudbansal** [comment]
Verified changes. There are discrepancies  in total hours.

**Comment by DeeptiNewput** [comment]
Update mentioned changes.It work's fine at our end.

**Comment by kumudbansal** [comment]
Verified. It is still showing incorrect value of total hours.

**Comment by kumudbansal** [comment]
This issue has been fixed and verified. Thanks. Closing.
