### ISSUE TITLE
Email copy changes for registration and reset password

### ISSUE THREAD

**Issue by kumudbansal** [Newput-Time-tracker/Web-app#137]
Please consider following copy changes for confirmation and reset password:-

1. Confirmation mail-

Subject:- Account activation

Content-  
Welcome username,

To be able to sign in to your account, please verify your email address first by clicking the following link:
Click Here..

Thanks,
Newput Infotech

2.  Reset Password-

Subject:- Reset your time-tracker account password

Content:-

User name,

We have received a request to reset the password of your account. If you made this request, please Click Here..

The password reset link is valid for 1 hour.
If you didn't raise this request, please ignore this email.

Thanks,
Newput Infotech

3. Notification mail-

Subject:- Reminder to fill time-sheet

Content:-

Hi, Please fill your time-sheet. You can login to time-tracker by clicking the following link:
Click Here.. 

Thanks,
Newput Infotech

**Comment by kumudbansal** [comment]
Please change the email copy when user mail time-sheet to himself.It should be something like 'Please find attached time-sheet'.

**Comment by DeeptiNewput** [comment]
Done with the changes.Please verify

**Comment by kumudbansal** [comment]
Please give line break in last line.

**Comment by kumudbansal** [comment]
Changes are looking good to me. Thanks. Closing.
