### ISSUE TITLE
Timesheet preview issue

### ISSUE THREAD

**Issue by kumudbansal** [Newput-Time-tracker/Web-app#150]

**Comment by kumudbansal** [comment]
Steps to reproduce:-
1. Email time sheet to your email id.
2. Click on time-sheet and observe preview of the time-sheet.

It is showing null value in all the fields of total hours.

**Comment by DeeptiNewput** [comment]
It can not be handle,It's a default behavior.

**Comment by kumudbansal** [comment]
Ok .Thanks.Closing.
