### ISSUE TITLE
Lunch time should be in range of day in and day out 

### ISSUE THREAD

**Issue by bansalsonam22** [Newput-Time-tracker/Web-app#151]
Day in     12:15    out 17:15
Lunch in  12:00    out 12:40
Night in    23:00   out 25:00

**total** 7:10 but actually it is 7:25

To fix this issue Lunch time should be in range of Day time.

**Comment by bansalsonam22** [comment]
One more issue for time calculation:
Enter below time
Day in 12:00 out 17:15
Lunch in 12:00 out 12:40
Night in 23:00 out 25:00

save it and go to edit it will show 25:00 as 01:00. If we press save button it will show error message. Show hours in edit mode as user has entered.

**Comment by kumudbansal** [comment]
First issue is fixed and verified.
