### ISSUE TITLE
Time sheet view UI changes

### ISSUE THREAD

**Issue by varshatyagi** [Newput-Time-tracker/Web-app#163]
1) changes the weekly dropdown
2) heading should be Timesheet - month name
3) No data message on timesheet when data is not availble 
4) move timesheet welcome text to header.

**Comment by kumudbansal** [comment]
Changes are looking good to me. Please add short description on logout button.

**Comment by varshatyagi** [comment]
Thanks. Description of logout button has been added. Please check.

**Comment by varshatyagi** [comment]
Thanks. Description has been added. Please check.

**Comment by kumudbansal** [comment]
Verified.
