### ISSUE TITLE
make week dropdown option less crowdy

### ISSUE THREAD

**Issue by shashank-saxena** [Newput-Time-tracker/Web-app#232]
instead of this :
2nd Week, Sunday,8th to Saturday,14th

try to do like:
Sun 8th to Sat 14th (2nd Week)

or something better but less crowdy

**Comment by kumudbansal** [comment]
Change copy from 'verify account' to 'verified account'.

**Comment by kumudbansal** [comment]
verified. Thanks. Closing.
