### ISSUE TITLE
Error message on registration page

### ISSUE THREAD

**Issue by kumudbansal** [Newput-Time-tracker/Web-app#240]
Please see attached screenshot. The error message should be changed, it should be something like 'Invalid Number Please enter valid 10 digit number'.
![capture9](https://cloud.githubusercontent.com/assets/15623790/11264887/99675eea-8ebd-11e5-9e01-a75d3b59832a.PNG)

**Comment by deeppatidar** [comment]
connect #242

**Comment by kumudbansal** [comment]
Changes are looking good to me. Thanks. Closing.
