### ISSUE TITLE
Fixed eslint issues on all JS files

### ISSUE THREAD

**Issue by shashank-saxena** [Newput-Time-tracker/Web-app#42]
@varshatyagi @deeppatidar 

This should be done when app functionality is done.

Steps to get the issues: 
1. npm install eslint -g
2. eslint app/scripts (current directory should be web-app)

**Comment by varshatyagi** [comment]
can we close this issue? as all the errors of es lint have been resolved.

**Comment by shashank-saxena** [comment]
yea, sure
