### ISSUE TITLE
Use font-awesome for font icons

### ISSUE THREAD

**Issue by shashank-saxena** [Newput-Time-tracker/Web-app#43]

**Comment by varshatyagi** [comment]
we are using bootstrap's glyphicon icons. can we use them ?

**Comment by shashank-saxena** [comment]
Yes we have to use font-awesome but that a lower priority issue

**Comment by varshatyagi** [comment]
Ok

**Comment by kumudbansal** [comment]
UI is distorting. Please see attached screenshot.

**Comment by kumudbansal** [comment]
Changes are looking good to me. Thanks. Closing.
