### ISSUE TITLE
Date picker issue on registration page

### ISSUE THREAD

**Issue by kumudbansal** [Newput-Time-tracker/Web-app#87]
Two date picker are opening when clicking on DOB or DOJ on registration page.

**Comment by varshatyagi** [comment]
i have fixed this issue, please test it.

**Comment by kumudbansal** [comment]
Verified changes. here is my points:-
1. Remove today button from both calendar.
2. Increase the width of the calendar.

**Comment by kumudbansal** [comment]
Changes are looking good to me. Thanks. Closing.
