### ISSUE TITLE
Error message on registration page

### ISSUE THREAD

**Issue by kumudbansal** [Newput-Time-tracker/Web-app#90]
Steps to reproduce:-
1. Go to registration page.
2. Click on password field and start typing password.

Observe the error message below the confirm password field, It is showing "Password and Confirm password are not equal!"  error message even if user not finished typing in password field and not clicked on confirm password field. Please see attached screenshot.
![registration_page](https://cloud.githubusercontent.com/assets/15623790/10903689/4f30332a-8232-11e5-931f-6078e40eb000.PNG)

**Comment by deeppatidar** [comment]
Created PR

**Comment by kumudbansal** [comment]
This issue has been fixed and verified. Thanks. Closing.
